version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: AchatDataBase   
    ports:
      - 3307:3307
    networks:
     - devops
     
  spring-boot:
    image: mariemmannai/achat:1.0
    container_name: springBack
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - devops 
    restart: on-failure     
  angular:
    image: mariemmannai/front
    container_name: Angularfront
    ports: 
      - 80:80
    depends_on:
      - spring-boot
    networks:
      - devops
  
networks:
  devops:
