version: '3.3'
services:
  db:
    image: mysql
    container_name: mysqlAchat
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: dbAchat   
    ports:
      - 3307:3307
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  spring-boot:
    image: rouamaknin/spring-achat
    container_name: springAchat
    ports:
      - 8089:8089
    depends_on:
      - db
    networks:
      - projectdevops  
    restart: on-failure
 
  
